# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Copy Environment Variables
        run: |
          echo "GH_PAT=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
      
      - name: Open Original Repository
        uses: actions/checkout@v4
        with:
          repository: 'AkeemSemper/Introduction_to_Machine_Learning_Student_Workbooks'
          ref: 'main'

          #token: ${{ secrets.GH_PAT }}
      - name: Check Rep
        run: |
          ls
          git status

      - name: Clone GuillaumeFalourd/poc-github-actions PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'AkeemSemper'
          repository: 'Intro_to_Machine_Learning_Full_Repo'
          access-token: ${{ secrets.GH_PAT }}

      - name: Access cloned repository content
        run: |
          # Check Status
          #ls -rf

          # Workbooks
          rm -rf workbooks
          mkdir workbooks
          cp -r Intro_to_Machine_Learning_Full_Repo/*.ipynb workbooks
          #ls -la workbooks

          # Images
          rm -rf images
          mkdir images
          cp -r Intro_to_Machine_Learning_Full_Repo/images/* images

          # Data

          # Resources
          rm -rf reference_content
          mkdir reference_content
          cp -r Intro_to_Machine_Learning_Full_Repo/reference_content/ reference_content

          # Clear
          rm -rf Intro_to_Machine_Learning_Full_Repo
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generated Update from Main Repository"
          git push --force
      # Commit all changed files back to the repository
      #- name: Commit files
        #uses: stefanzweifel/git-auto-commit-action@v5
        #with:
          #repository: 'AkeemSemper/Programming_for_ML_Student_Workbooks'
          #owner: 'AkeemSemper'
          #repository: 'Programming_for_ML_Student_Workbooks'
          #commit_options: '--no-verify --signoff'
          #branch: main
          #token: ${{ secrets.GH_PAT }}
          #commit_message: "Update files from Base Repository"
          #skip_dirty_check: true